service: carbon-registry-services

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
  iam:
    role: arn:aws:iam::302213478610:role/lambda-role
  vpc:
    subnetIds:
      - subnet-0f01c3493bfdaabd7
      - subnet-029725efdcd399b88
    securityGroupIds:
      - sg-029b80f0fd44eb16a

package:
  patterns:
    - "!node_modules/**"
    - ".env"
    - .env.${self:provider.stage}
    - "countries.json"

plugins:
  - "serverless-plugin-typescript"
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-ssm-fetch
#  - '@haftahave/serverless-ses-template'

params:
  local:
    depLayerArn1: arn:aws:lambda:us-west-2:111111111111:layer:layer:1
    depLayerArn2: arn:aws:lambda:us-west-2:111111111111:layer:layer:1

functions:
  national-api:
    timeout: 300
    handler: src/national-api/handler.handler
    events:
      - http:
          method: any
          path: /api/national/{any+}
    ssmToEnvironment:
      - DB_PASSWORD
      - USER_JWT_SECRET
      - ADMIN_JWT_SECRET
      - SES_PASSWORD
    environment:
      NODE_PATH: "./:/opt/node_modules"
    layers:
      - ${param:depLayerArn1}
      - ${param:depLayerArn2}

  analytics-api:
    timeout: 300
    handler: src/analytics-api/handler.handler
    events:
      - http:
          method: any
          path: /api/stats/{any+}
    ssmToEnvironment:
      - DB_PASSWORD
      - USER_JWT_SECRET
      - ADMIN_JWT_SECRET
      - SES_PASSWORD
    environment:
      NODE_PATH: "./:/opt/node_modules"
    layers:
      - ${param:depLayerArn1}
      - ${param:depLayerArn2}

  replicator:
    timeout: 60
    handler: src/ledger-replicator/handler.handler
    events:
      - stream:
          arn: arn:aws:kinesis:us-east-1:302213478610:stream/carbon-stream-dev
          batchSize: 2
          startingPosition: LATEST
          maximumRetryAttempts: 10
          enabled: true
    ssmToEnvironment:
      - DB_PASSWORD
    environment:
      NODE_PATH: "./:/opt/node_modules"
    layers:
      - ${param:depLayerArn1}
      - ${param:depLayerArn2}

  setup:
    timeout: 60
    handler: src/setup/handler.handler
    ssmToEnvironment:
      - DB_PASSWORD
      - SES_PASSWORD
    environment:
      NODE_PATH: "./:/opt/node_modules"
    layers:
      - ${param:depLayerArn1}
      - ${param:depLayerArn2}

  default:
    handler: src/shared/handler.handler
    events:
      - http:
          method: any
          path: /{any+}
    environment:
      NODE_PATH: "./:/opt/node_modules"
    layers:
      - ${param:depLayerArn1}
      - ${param:depLayerArn2}
custom:
  optimize:
    external: ["swagger-ui-dist"]
  serverlessSsmFetch:
    DB_PASSWORD: /${self:provider.stage}/DB_PASSWORD~true
    USER_JWT_SECRET: /${self:provider.stage}/USER_JWT_SECRET~true
    ADMIN_JWT_SECRET: /${self:provider.stage}/ADMIN_JWT_SECRET~true
    SES_PASSWORD: /${self:provider.stage}/SES_PASSWORD~true
  # sesTemplates:
  #   addStage: true                             # Specifies whether to add stage to template name (default false)
  #   configFile: './src/shared/email/email.template.ts' # Config file path (default './ses-email-templates/index.js')
  #   region: 'us-east-1'
